export enum StorageKeys {
  COUNTRIES = "COUNTRIES",
  TOKEN_SERVICES = "TOKEN_SERVICES",
  PROFILE_SERVICES = "PROFILE_SERVICES",
  CATEGORI_SERVICES = "CATEGORI_SERVICES",
  OPEN_LIST = "OPEN_LIST",
  CONFIG = "CONFIG"
}
